spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-wait: -1
        max-idle: 10
        max-active: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false #禁用缓存
    encoding: UTF-8
    prefix: classpath:/views/
    suffix: .html
    mode: HTML
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #配置德鲁伊连接池
      initial-size: 5

      min-idle: 5

      max-active: 20

      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,wall,log4j2,config
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      url: jdbc:mysql://localhost:3306/biyesheji?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8443
  ssl:
    #配置ssl 启用https
    key-store: classpath:baikun.p12
    key-store-type: PKCS12
    key-alias: baikun
    key-store-password: 123456
  servlet:
    encoding:
      charset: UTF-8
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句
user:
  filepath: E://clzyproject/biyesheji/upload/ #是两个//